In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

In [2]:
data=pd.read_csv("/kaggle/input/usa-cers-dataset/USA_cars_datasets.csv")
data

,Unnamed: 0,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,0,6300,toyota,cruiser,2008,clean vehicle,274117.0,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,1,2899,ford,se,2011,clean vehicle,190552.0,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,2,5350,dodge,mpv,2018,clean vehicle,39590.0,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,3,25000,ford,door,2014,clean vehicle,64146.0,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,4,27700,chevrolet,1500,2018,clean vehicle,6654.0,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2494,7800,nissan,versa,2019,clean vehicle,23609.0,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
2495,2495,9200,nissan,versa,2018,clean vehicle,34553.0,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2496,2496,9200,nissan,versa,2018,clean vehicle,31594.0,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2497,2497,9200,nissan,versa,2018,clean vehicle,32557.0,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2498,2498,9200,nissan,versa,2018,clean vehicle,31371.0,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2499 entries, 0 to 2498
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    2499 non-null   int64
 1   price         2499 non-null   int64
 2   brand         2499 non-null   object
 3   model         2499 non-null   object
 4   year          2499 non-null   int64
 5   title_status  2499 non-null   object
 6   mileage       2499 non-null   float64
 7   color         2499 non-null   object
 8   vin           2499 non-null   object
 9   lot           2499 non-null   int64
 10  state         2499 non-null   object
 11  country       2499 non-null   object
 12  condition     2499 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 253.9+ KB

In [5]:
data=pd.get_dummies(data,drop_first=True)
data

,Unnamed: 0,price,year,mileage,lot,brand_audi,brand_bmw,brand_buick,brand_cadillac,brand_chevrolet,...,condition_5 hours left,condition_53 minutes,condition_6 days left,condition_6 hours left,condition_7 days left,condition_7 hours left,condition_8 days left,condition_9 days left,condition_9 minutes,condition_Listing Expired
0,0,6300,2008,274117.0,159348797,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,2899,2011,190552.0,166951262,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,2,5350,2018,39590.0,167655728,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,3,25000,2014,64146.0,167753855,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,4,27700,2018,6654.0,167763266,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2494,7800,2019,23609.0,167722715,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2495,2495,9200,2018,34553.0,167762225,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2496,2496,9200,2018,31594.0,167762226,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2497,2497,9200,2018,32557.0,167762227,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2498,2498,9200,2018,31371.0,167762228,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
selected_features=['year','mileage','lot']
x=data[selected_features]
y=data['price']

In [11]:
x_train,x_test, y_train,y_test = train_test_split(x,y, train_size=0.2, random_state=42)

In [12]:
model=LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [13]:
y_pred=model.predict(x_test)

In [14]:
mse=mean_squared_error(y_test, y_pred)
r2=r2_score(y_test, y_pred)

In [15]:
print(f'MEAN SQUARED ERROR: {mse}')
print(f'R2 SCORE : {r2}')

MEAN SQUARED ERROR: 123755959.60973093
R2 SCORE : 0.15680004952800286